version: ""

formatter: markdown table

name: terraform-aws-multiaccount-pipeline

content: |-
  # Terraform Multiaccount Pipeline

  [StratusGrid/terraform-aws-multiaccount-pipeline](https://github.com/StratusGrid/terraform-aws-multiaccount-pipeline)

  Terraform module to create a CICD pipeline for Terraform which can execute from a Production or CICD account across multiple sub-accounts which each contain a specific environment.

  ---

  ## Example with S3 bucket source

  ```hcl
  {{ include "examples/s3_source/main.tf" }}
  ```

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Contributors
  - Christopher Childress [chrischildresssg](https://github.com/chrischildresssg)
  - Ivan Casco [ivancasco-sg](https://github.com/ivancasco-sg)

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: test_output.md
  mode: insert
